### ISSUE TITLE
problem with uses classintervals for size point R plot

### ISSUE THREAD

**Issue by westabra** [oscarperpinan/bookvis#69]
1) I try make spatial map with classes size of spatial points Simply i repeat workflow from monography: Displaying time series, spatial, and space-time data with R / Oscar Perpiñán Lamigueiro. see chapter 8.4 Optimal Classification to Improve Discrimination. Start of script:

```
library(sp)
library(rgdal) 
Issano_Gap_Rocks <- read_excel("Issano Gap Rocks Original File_for_plot.xls")
xy <- Issano_Gap_Rocks[,c('EASTING', 'NORTHING')]
Issano_spdf_Rocks <- SpatialPointsDataFrame(coords = xy, data = Issano_Gap_Rocks,proj4string = CRS("+init=epsg:24821"))
 library(classInt)
airPal_Rock <- colorRampPalette(c("green", "yellow","red"))(5)
op <- options(digits=4)
tab <- print(intervals)
options(op)
nClasses <- 5
intervals <- classIntervals(Issano_spdf_Rocks$Sc_ppm_INAA, n = nClasses, style = "quantile")
tab <- print(intervals)
nClasses <- length(intervals$brks) -1
dent <- c(0.64, 1.14, 1.65, 2.79, 4.32, 6.22, 9.65, 12.95, 15.11) #point size 
dentAQ <- dent[seq_len(nClasses)]
idx <- findCols(intervals)
cexNO2 <- dentAQ[idx]
Issano_spdf_Rocks$classNO2 <- factor(names(tab)[idx])
```
2)But after all my classes of point not regular ranged by value Sc_ppm_INAA. Look as mismatch: the max interval placed in wrong position. I dont understanding were my mistake?
The same issue I get if did prepare plot in GGPLOT version. So as i guess problem with code about divide data to classes
![vd54H](https://user-images.githubusercontent.com/50172502/127330979-fa41b3bd-7bae-4db1-9480-a5454b6c31b4.png)
![BmoCF](https://user-images.githubusercontent.com/50172502/127331066-590af88f-c4c9-4a24-b575-d1353123c2d6.png)

**Comment by oscarperpinan** [comment]
Hello,

I need the data to check the result. Please attach a CSV file with your data.

**Comment by westabra** [comment]
Okay, please find attached file.Just in case, the name of the local grid system : proj4string = CRS("+init=epsg:24821"))Thanks in advanceSergey Abramov06.08.2021, 14:29, "Oscar Perpiñán Lamigueiro" ***@***.***>: Hello,I need the data to check the result. Please attach a CSV file with your data.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.  -- Regards, Sergei

**Comment by westabra** [comment]
[Issano_df.csv](https://github.com/oscarperpinan/bookvis/files/6986478/Issano_df.csv)

**Comment by oscarperpinan** [comment]
I think you have sent a file with different data from your example. These are the intervals I get:

```
> intervals
style: quantile
  one of 211,876 possible partitions of this variable into 5 classes
 [0.6,2.66) [2.66,4.14) [4.14,6.86) [6.86,9.08) [9.08,16.3] 
         13          13          12          13          13 

```

![Issano](https://user-images.githubusercontent.com/1321370/129721305-42f90c7a-2cb5-4366-88ab-c45ee24b22d6.png)

This is the code I am using:

```
library(sp)
library(rgdal)
library(classInt)

Issano <- read.csv("/tmp/Issano_df.csv")
xy <- Issano[, c("East", "North")]
dats <- Issano[, c("La_ppm", "Sc_ppm")]

Issano_spdf_Rocks <- SpatialPointsDataFrame(coords = xy,
                                            data = dats,
                                            proj4string = CRS("+init=epsg:24821"))


nClasses <- 5
airPal_Rock <- colorRampPalette(c("green", "yellow","red"))(nClasses)


intervals <- classIntervals(Issano_spdf_Rocks$Sc_ppm,
                            n = nClasses,
                            style = "quantile")
tab <- print(intervals)
nClasses <- length(intervals$brks) -1
dent <- c(0.64, 1.14, 1.65, 2.79, 4.32, 6.22, 9.65, 12.95, 15.11) #point size 
dentAQ <- dent[seq_len(nClasses)]
idx <- findCols(intervals)
cexNO2 <- dentAQ[idx]
Issano_spdf_Rocks$classSc <- factor(names(tab)[idx])

IssanoKey <- list(x = 0.99, y = 0.01, corner = c(1, 0),
               title = "Sc_ppm",
               cex.title = 0.8, cex = 1,
               background = 'gray92')

spplot(Issano_spdf_Rocks["classSc"],
       col.regions = airPal_Rock,
       cex = dentAQ * 0.8,
       edge.col = 'black',
       scales = list(draw = TRUE),
       key.space = IssanoKey)

```

**Comment by westabra** [comment]
Thanks a lot!Works!My sample dataset  when doing gave an error  in the order of intervales (as I wrote  first time). Whatever I do. But  the example that I sent you was running normal, as it should. I felt like an idiot. Then, for the sake of interest, I d combined these two datasets and after selected the necessary data as a subset. Everything  started doing properly! It seems like I vaccinated my dataset :))Well, I also tested  Yours code on larger dataset(about 300 samples), everything is considered and plotted normallyThanks!Regard Sergei Abramov 17.08.2021, 14:56, "Oscar Perpiñán Lamigueiro" ***@***.***>: I think you have sent a file with different data from your example. These are the intervals I get:> intervals
style: quantile
  one of 211,876 possible partitions of this variable into 5 classes
 [0.6,2.66) [2.66,4.14) [4.14,6.86) [6.86,9.08) [9.08,16.3] 
         13          13          12          13          13 

This is the code I am using:library(sp)
library(rgdal)
library(classInt)

Issano <- read.csv("/tmp/Issano_df.csv")
xy <- Issano[, c("East", "North")]
dats <- Issano[, c("La_ppm", "Sc_ppm")]

Issano_spdf_Rocks <- SpatialPointsDataFrame(coords = xy,
                                            data = dats,
                                            proj4string = CRS("+init=epsg:24821"))


nClasses <- 5
airPal_Rock <- colorRampPalette(c("green", "yellow","red"))(nClasses)


intervals <- classIntervals(Issano_spdf_Rocks$Sc_ppm,
                            n = nClasses,
                            style = "quantile")
tab <- print(intervals)
nClasses <- length(intervals$brks) -1
dent <- c(0.64, 1.14, 1.65, 2.79, 4.32, 6.22, 9.65, 12.95, 15.11) #point size 
dentAQ <- dent[seq_len(nClasses)]
idx <- findCols(intervals)
cexNO2 <- dentAQ[idx]
Issano_spdf_Rocks$classSc <- factor(names(tab)[idx])

IssanoKey <- list(x = 0.99, y = 0.01, corner = c(1, 0),
               title = "Sc_ppm",
               cex.title = 0.8, cex = 1,
               background = 'gray92')

spplot(Issano_spdf_Rocks["classSc"],
       col.regions = airPal_Rock,
       cex = dentAQ * 0.8,
       edge.col = 'black',
       scales = list(draw = TRUE),
       key.space = IssanoKey)

**Comment by oscarperpinan** [comment]
Good news!
